AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - lib/generators/**/*.rb
    - gemfiles/*
    - spec/**/*
    - examples/*

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
