---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/**/*
    - lib/generators/**/*.rb

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/OptionalBooleanParameter:
  Exclude:
    - lib/crono/sd_notify.rb

Style/RescueStandardError:
  Enabled: false

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 125

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

##########
# NAMING #
##########

Naming/BlockForwarding:
  Enabled: false
