language: ruby
cache: bundler
sudo: false
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - ruby-head
gemfile:
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.7.gemfile
  - gemfiles/rails_5.2.4.gemfile
  - gemfiles/rails_6.0.1.gemfile
matrix:
  exclude:
    - gemfile: gemfiles/rails_6.0.1.gemfile
      rvm: 2.4.9
  allow_failures:
    - rvm: ruby-head
