language: ruby
cache: bundler
sudo: false
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - ruby-head
gemfile:
  - gemfiles/rails_5.1.7.gemfile
  - gemfiles/rails_5.2.4.gemfile
  - gemfiles/rails_6.0.2.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
