#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/crono'

# rubocop:disable Style/StderrPuts
begin
  cli = Crono::CLI.instance
  cli.parse
  cli.integrate_with_systemd
  cli.run
rescue => e
  raise e if $DEBUG

  $stderr.puts e.message
  $stderr.puts e.backtrace.join("\n")
  exit 1
end
# rubocop:enable Style/StderrPuts
