#!/usr/bin/env ruby
# frozen_string_literal: true

require 'crono/cli'

begin
  Crono::CLI.instance.run(ARGV)
rescue => e
  raise e if $DEBUG
  STDERR.puts e.message
  STDERR.puts e.backtrace.join("\n")
  exit 1
end
